// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://xkjqkqgmyhgdpqrbuvph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhranFrcWdteWhnZHBxcmJ1dnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzMDYxNzcsImV4cCI6MjA4MDg4MjE3N30.by0IhkXikFoEF5aImMsusEEndmVU5LKmgWttyvfg0eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
