// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzerlqbuaepmpvohxrvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZXJscWJ1YWVwbXB2b2h4cnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjYxNTgsImV4cCI6MjA2NDAwMjE1OH0.VWHqdIxPaJZ9U15g_AB4czhY8eY8prZBcRh5BjW5xtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
